"""create api_processes table

Revision ID: 17f9ff8fb175
Revises: a5b4c453cb78
Create Date: 2025-10-03 14:54:31.717172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f9ff8fb175'
down_revision = 'a5b4c453cb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('payload_count', sa.Integer(), nullable=True),
    sa.Column('status_ok', sa.Boolean(), nullable=True),
    sa.Column('result_pdf', sa.String(length=255), nullable=True),
    sa.Column('result_json', sa.Text(length=4294967295), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_processes')
    # ### end Alembic commands ###
